### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/forgeApp#20]
@mikehylland this application is ready for you to review when you have time.

https://geology.utah.gov/apps/jay/tests/FORGE/

**Comment by mikehylland** [comment]
A few observations:

1. Under FORGE Infrastructure, Well Pads: The pads for 16-32 and 56-32 are shown in the explanation as diagonal lines, but show on the map as dark gray fill. The light gray fill for the other pads looks good (is consistent between explanation and map). One other thing: on my monitor view, the explanation text is cut off on the right side (e.g., 78-?? ??? Pad), and I can't see that I'm able to expand the explanation box.

2, For both Well Pads and Wells, I don't suppose there's a way to eliminate the redundancy in patterns/symbols in the explanation (i.e., three identical well symbols all with the same listing of associated wells)?

3. Under Wells, what does "<all other values>" refer to?

4. Under Geology, do the geologic units need to be numbered? Unclear what the purpose is, and seems unusual. Also, more issues with cut-off text on the right side of the explanation box.

5. Under Geology, the data table opens up to the entry for unit Mhd, but that's it. I don't seem to be able to scroll through the table (should I be able to access data for other units in this view?). Also, only part of the unit description shows up (it appears to be truncated at the bottom of the screen). I also see that this same partial table (for unit Mhd) opens up when I click on "Data Table" under Wells.

**Comment by mikehylland** [comment]
Observations/questions cont.:

7. Subsurface Bedrock: This data category seems to require some explanation, as theoretically there is subsurface bedrock across the entire map area. Is this bedrock beneath Q deposits and at some particular depth below the ground surface, or ? Also, the polygons for this unit change with changing zoom levels.

8. Geography section looks good. One question: For the roads, can "all other values" be changed to something like "Other Roads"?

9. Under Thermal Data: Any chance of making the well symbols for deep, intermediate, and shallow different colors? It would be helpful when all three data layers are being viewed at the same time to be able to visually differentiate the three depth categories. BTW, the linked temperature profile plots are awesome!

10. Heat Flow Isotherms: What exactly are these (i.e., how do they differ from the isotherms at specific depths)? Is there some clarifying comment that needs to be added to the explanation? Also, what are the units of measure for these?

11. For Isotherms at Xkm Depth, indicate units (i.e., °C, correct?).

12. Like for the different well depth categories, any chance of making the isotherms at different depths different colors? Again, would be helpful for seeing spatial pattern changes when all four depth categories are being viewed at the same time.

**Comment by Stefankirby** [comment]
Below are responses to Mike Hyllands Review comments.  

1.For Jay or Martha.  Lets have all the pads be light gray.
2.For Jay or Martha.  Change the 16A-32 well symbol to black.  In the explanation black well symbols = Existing wells, red well symbols = Proposed wells
3.For Jay or Martha Remove all other well type from the explanation
4.For Jay or Martha the data table is complete so far no changes needed, depth should noted as meters
5.For Martha,  Do these have to be numbered?  Its not required as far as I am concerned.
6.For Jay and Martha,  Geology data table looks fine to me.  But is there a way for it to show the screen selected unit in the table?
7.For Jay or Martha, Lets rename Subsurface Bedrock to "Top of Bedrock Surface"
8.For Jay or Martha, Change all other values to "Other Roads"
9.For Jay or Martha,  Would it be possible to change shallow wells to yellowish, intermediate wells to orangish, and deep wells to red
10.For Jay or Martha, Change Heat flow isotherms to Heat Flow "(W/m^2)" also labeling of lines was spotty for me is there a way to improve this?
11.For Jay or Martha, units should be (°C)
12.For Jay or Martha,  Would it be possible to make different colors for the different depths?  Start at yellow for shallow and then grade to reddish for deep.  In a manner similar to that for the thermal wells?

**Comment by jjhi11** [comment]
5. Fixed the legend box width so it doesn't cut off any descriptions. Numbering them makes sure they are ordered according the age.

6. Fixed

**Comment by mikehylland** [comment]
Observations/questions cont.:

13. Seismic Data: Consider changing this heading to "Seismicity Data," which is more specific to earthquakes (vs. other sources of ground shaking, seismic reflection/refraction analyses, etc.).

14. Seismicity 1850 to 2016, Data Table: Please indicate units of measure for Depth. Also, I don't see any cell entries under Month(?). Also, should there be location data for these events? I'm not sure what these data represent; I'm only seeing data for ~40 events, and these are all from a timeframe of two years (2009 and 2010). Is the table acting up, or ?

15. For the seismicity map symbols, recommend adding "M" before the magnitude numbers.

16. Geophysical Data, Bouger Gravity: Awesome looking map! Please add units of measure to the explanation.

17. Bouger_Grav_RasInteger: Is this something that should show up in the explanation? I don't see any specific data associated with it(?).

18. Geophysical Benchmarks: Should these have static IDs shown on the map, or in pop-up windows, or? In the data table, I don't see a way to associate a Point ID with a specific benchmark on the map. Also, in the table, please add unit of measure for Elevation.

**Comment by mikehylland** [comment]
Observations/questions cont.:

19. Under Groundwater, please add units of measure for the Water Chemistry data categories in the explanation. The data in the pop-up windows mostly looks great; however, for the temperature data, please delete the space between the degree symbol and "C" and capitalize "C" (i.e., standard SI symbol for Celsius).

20. Water Chemistry, Data Table: Please specify unit of measure for Temperature. Also, are the "invalid dates" something that can be fixed?

21. Water Levels: In the pop-up window data, please specify unit of measure for water levels and depths. Likewise for Water Elevation in the Data Table. (Also, same question for "invalid dates" as in the Water Chem Data Table.)

22. For Water Levels, some general comments on the utility of the map symbols and data table: The well IDs on the map are superimposed over the well symbols, so they're hard to read. The data table gives the full well name rather than the ID used on the map, so it's hard to associate the data in the table with the location of the well on the map. The data table lists Water Elevation and Date Measured, but those data are also given in the well's pop-up window. Is there a way to download the data table (this applies to all of the data tables) as a csv file (or other)? If not, the table seems redundant with the pop-up windows and of limited utility. What's the desired purpose of the data table?

23. Measure Tool: This seems like a handy feature that could add some value to the app. And the fact that units of measure show up along with the numbers makes me happy! But, I seemed to encounter a couple possible glitches. Maybe just user error? :P 
- I open the Measure Tool dialog box, make my two measurement clicks and a nice bar graphic appears along with a useful measurement summary in the dialog box. Now I want to move on, so I close the dialog box but the bar graphic remains. I click on the map and it still doesn't go away. I re-open the dialog box and click "new measurement" (even though I don't want to make a new measurement) and the bar graphic disappears. Okay, good. I close the dialog box, and then happen to make two random clicks on the map, and a new bar graphic appears. D'oh! Is there some way to exit out of the tool and make the bar graphic disappear that I'm missing?
- When I have the Measure Tool open and hover the cursor over certain parts of the map, some strange polygon boundary lines show up that move around as I move the cursor. What are those (topo contour lines maybe, or ?)? Also, if one of my measurement click points is in one of these areas, I get a bar graphic that shows all three measurement parameters, rather than just the direct distance parameter that shows up if I make a measurement somewhere else. Is the tool working correctly in this case?

**Comment by Stefankirby** [comment]
Below are responses to Mike Hyllands Review comments.  These can be dealt with either by Martha or Jay

13.  Follow Hylland's comment

14.  Units of depth are in KM, If there is no data for month then remove this field, Also check this data versus the old webmap,  Hylland does seem to be correct that data is missing.  Give me a call when you get to this part.
 
15.  Add M per comment

16. Add units as "mGal"

17.  Follow comment remove Bouger

18.  Add static ID's for each benchmark that follow input file.

19.  Follow Hyllands comments,  I have already shared a table of units with Jay for this part.  Call me with questions.

20.  See previous comment answer.  Check invalid dates against the original file on old webmap.  call me with questions.

21.  Unit of measurement for DTW is feet below land surface, Unit of measurement for water elevation is feet

22.  This one is complicated we should look at it together call me when you get here.

23.  Just check that the measurement tool works as it should,  most of these comments seem to concern user operation issues not the tool.  But check this out anyway.

Thanks for all the work.  Call me as you have questions.

**Comment by marthajensen** [comment]
1-3 fixed

4 @jjhi11 new field called depth_m - has a "m" after each value in the field

5 removed numbers on geologic units

7 - @jjhi11  I think the layer name  is hardcoded in the app

8 fixed

9 @jjhi11 I changed the colors of the underground 3d wells, but the new colors aren't showing in the app. Any ideas? Shallowest wells should be yellow, while deepest should be red (The symbol for the 2d wells (above ground) have been changed to this color scheme as well). I made a new test shallow layer to see if AGOL isn't allowing overwriting of these layers. The new test 3d layer for shallow wells is: https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/Thermal_Shallow_Wells/SceneServer

10-11 @jjhi11  I changed the heat flow layer name and added the units - can you pull these values into the layer name in the app? See below
![image](https://user-images.githubusercontent.com/11522897/100631113-9d6e8700-32e8-11eb-82f3-5971ade4abbb.png)

12. fixed

**Comment by jjhi11** [comment]
Numbers 4, 7 and 9 but please check #10 and 11 to be sure they have been fixed to what was described

**Comment by Stefankirby** [comment]
For 10 and 11 I don't see the unit changes on the webmap.   But your solution above would work just add the units to the respective layer labels.

Thanks!

**Comment by marthajensen** [comment]
13 @jjh11 I think this is hardcoded in the app
14. There are 2415 features in the AGOL service - I think the table in the app is acting up. If I click on the Year heading, the table shows more data points, but still doesn't show all of the data points in the AGOL service.  There is a value for month in the AGOL service too - I'm not sure why its not showing in the app
15 fixed - M added to legend
16 - New Bouger gravity layer with corrected legend symbology (the legend in the app right now isn't showing the right values) https://tiles.arcgis.com/tiles/ZzrwjTRez6FJiOq4/arcgis/rest/services/Bouger_Tile_mGal/MapServer
Also, Stefan was wondering if we could add the units - mGal -  to the layer name in the legend?
17. ?
18. Added point id labels to each benchmark. Added the elevation value of (m) to the field name - the alias for the field is now Elevation (m). The alias isn't showing in the app though (@jjh11)

**Comment by jjhi11** [comment]
13. fixed
14. fixed
15. Had to add it to the title
16. Added to title
17. Fixed
18. @marthajensen thanks
19. Fixed
20. Fixed
21. Fixed

still working on the last two

**Comment by jjhi11** [comment]
22. added ID field to data table
23. the interface has been improved

**Comment by Stefankirby** [comment]
A.  For the Roads layer could they be clickable with their name?  and could they just be labeled as roads in the legend?

B.  Add units "(°C)" for each of the isotherm layer titles. It doesn't show for me.

C.  Measure Tool is not working in 3D.  Check.

D.  Add water level contour layer.  This was on previous versions of the map.

**Comment by marthajensen** [comment]
B. I added "°C" to each of the isotherm labels
D. @Stefankirby I can't find the water level contour layer. I looked in our old webmap "U:\UGSSharedResources\FORGEwebmap_Archived\real_FORGE_webmap_update\realFORGEwebmap\realFORGEwebmap.aprx"
but I may have overlooked it. What is the layer name?

**Comment by jjhi11** [comment]
A, B, and C are addressed but havent heard on issue D.

**Comment by marshallrobinson** [comment]
Thanks for the thorough review Mike, I believe all of your comments have been addressed. Thanks to Martha, Stefan, Jay. I'll pass this on to Bill next.
